ALTER TABLE tbOrder
ADD CONSTRAINT fk_idProduct
FOREIGN KEY (idProduct)
REFERENCES tbProduct(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE tbOrder
ADD CONSTRAINT fk_idTransaction_1
FOREIGN KEY (idTransaction)
REFERENCES tbTransaction(id)
ON DELETE CASCADE
ON UPDATE CASCADE;


ALTER TABLE tbTransaction
ADD CONSTRAINT fk_idClient
FOREIGN KEY (idClient)
REFERENCES tbClient(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE tbBonusCard
ADD CONSTRAINT fk_idTransaction
FOREIGN KEY (idTransaction)
REFERENCES tbTransaction(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE tbBonusCard
ADD CONSTRAINT fk_idClient_1
FOREIGN KEY (idClient)
REFERENCES tbClient(id)
ON DELETE CASCADE
ON UPDATE CASCADE;